In [1]:
import pandas as pd  

In [2]:
from pandas import Series,DataFrame

In [3]:
obj = pd.Series([4,7,-5,3],index = ["a","b","c","d"])

In [4]:
obj

a    4
b    7
c   -5
d    3
dtype: int64

In [5]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
obj["b"]

7

In [7]:
obj >0

a     True
b     True
c    False
d     True
dtype: bool

In [8]:
obj[obj>0]

a    4
b    7
d    3
dtype: int64

In [9]:
 import numpy as np

In [10]:
np.exp(obj)

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [11]:
sdata = {"Ohio":3500,"Texas":7100,"Oregon":1600}

In [12]:
sdata

{'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600}

In [13]:
obj3 = pd.Series(sdata)

In [14]:
obj3

Ohio      3500
Texas     7100
Oregon    1600
dtype: int64

In [15]:
obj3.to_dict()

{'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600}

In [16]:
obj3

Ohio      3500
Texas     7100
Oregon    1600
dtype: int64

In [17]:
obj3 = obj3.to_dict()

In [18]:
obj3["Guiy"]=8900

In [19]:
obj3

{'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600, 'Guiy': 8900}

In [20]:
obj4 = pd.Series(obj3)

In [21]:
states = obj4.index

In [22]:
sates

NameError: name 'sates' is not defined

In [ ]:
states

In [ ]:
states=str(states)

In [ ]:
states

In [ ]:
state

In [ ]:
sdata

In [ ]:
sdata["Gui"] = 8900


In [ ]:
sdata

In [ ]:
state = ["Ohio","Gui","Texas","Si"]

In [ ]:
obj4 = pd.Series(sdata,index=state)

In [ ]:
obj4 #state中没有Oregon生成新的series会去除,按照index指定顺序呈现，Si没有值，在Series中表示为NaN

In [ ]:
pd.isna(obj4)

In [ ]:
pd.notna(obj4)

In [ ]:
obj4.isna()

In [ ]:
obj4.notna()

In [ ]:
obj3

In [ ]:
obj3=pd.Series(obj3)

In [23]:
obj3,obj4

({'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600, 'Guiy': 8900},
 Ohio      3500
 Texas     7100
 Oregon    1600
 Guiy      8900
 dtype: int64)

In [24]:
obj3 = obj3.rename(index={"Guiy":"Gui"})

AttributeError: 'dict' object has no attribute 'rename'

In [25]:
obj3

{'Ohio': 3500, 'Texas': 7100, 'Oregon': 1600, 'Guiy': 8900}

In [26]:
obj4

Ohio      3500
Texas     7100
Oregon    1600
Guiy      8900
dtype: int64

In [27]:
obj3+obj4 #Series算数运算中能自动对齐索引标签

TypeError: unsupported operand type(s) for +: 'dict' and 'int'

In [ ]:
obj4.name = "population"

In [ ]:
obj4.index

In [ ]:
obj4.index.name="state"

In [ ]:
obj4

In [ ]:
obj = pd.Series([4,7,8,9])

In [ ]:
obj

In [ ]:
obj.index=["Bob","Jay","Steve","Ryan"]

In [ ]:
obj

In [28]:
obj = obj.rename(index={"Bob":"Boby"})

In [29]:
obj

a    4
b    7
c   -5
d    3
dtype: int64

In [30]:
data={"State":["Ohio","Ohio","Ohio","Gui","Gui","Gui"],
      "year":[2000,2001,2002,2001,2002,2003],
      "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}

In [31]:
frame = pd.DataFrame(data)

In [32]:
frame

State  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6
3   Gui  2001  2.4
4   Gui  2002  2.9
5   Gui  2003  3.2

In [33]:
frame.head()

State  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6
3   Gui  2001  2.4
4   Gui  2002  2.9

In [34]:
frame.tail()

State  year  pop
1  Ohio  2001  1.7
2  Ohio  2002  3.6
3   Gui  2001  2.4
4   Gui  2002  2.9
5   Gui  2003  3.2

In [35]:
pd.DataFrame(data,columns=["year","State","pop"])

year State  pop
0  2000  Ohio  1.5
1  2001  Ohio  1.7
2  2002  Ohio  3.6
3  2001   Gui  2.4
4  2002   Gui  2.9
5  2003   Gui  3.2

In [36]:
frame2 = pd.DataFrame(data,columns = ["year","State","pop","debt"])

In [38]:
frame2

year State  pop debt
0  2000  Ohio  1.5  NaN
1  2001  Ohio  1.7  NaN
2  2002  Ohio  3.6  NaN
3  2001   Gui  2.4  NaN
4  2002   Gui  2.9  NaN
5  2003   Gui  3.2  NaN

In [40]:
print(frame2.index)

RangeIndex(start=0, stop=6, step=1)


In [41]:
frame2.columns

Index(['year', 'State', 'pop', 'debt'], dtype='object')

In [42]:
frame2["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [44]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [46]:
frame2.loc[1]

year     2001
State    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [48]:
frame2.iloc[0]

year     2000
State    Ohio
pop       1.5
debt      NaN
Name: 0, dtype: object

In [51]:
frame2.iloc[0]["debt"]=16

/var/folders/24/vsst64dn2h9b10q5jf4glt280000gn/T/ipykernel_66550/893101420.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame2.iloc[0]["debt"]=16


In [53]:
a = pd.Series([1,2,3,4],index=["a","b","c","d"])

In [54]:
a

a    1
b    2
c    3
d    4
dtype: int64

In [55]:
a["a"]

1

In [56]:
a["a"]=5

In [57]:
a

a    5
b    2
c    3
d    4
dtype: int64

In [58]:
frame2

year State  pop debt
0  2000  Ohio  1.5  NaN
1  2001  Ohio  1.7  NaN
2  2002  Ohio  3.6  NaN
3  2001   Gui  2.4  NaN
4  2002   Gui  2.9  NaN
5  2003   Gui  3.2  NaN

In [67]:
frame2["debt"]=[16,20,17,19,20,11]

In [68]:
frame2

year State  pop  debt
0  2000  Ohio  1.5    16
1  2001  Ohio  1.7    20
2  2002  Ohio  3.6    17
3  2001   Gui  2.4    19
4  2002   Gui  2.9    20
5  2003   Gui  3.2    11

In [69]:
frame2["debt"] = np.arange(6.)

In [70]:
frame2

year State  pop  debt
0  2000  Ohio  1.5   0.0
1  2001  Ohio  1.7   1.0
2  2002  Ohio  3.6   2.0
3  2001   Gui  2.4   3.0
4  2002   Gui  2.9   4.0
5  2003   Gui  3.2   5.0

In [71]:
val = pd.Series([-1.2,-1.5,-1.7],index=["two","threre","five"])

In [72]:
frame2["debt"] = val

In [73]:
frame2

year State  pop  debt
0  2000  Ohio  1.5   NaN
1  2001  Ohio  1.7   NaN
2  2002  Ohio  3.6   NaN
3  2001   Gui  2.4   NaN
4  2002   Gui  2.9   NaN
5  2003   Gui  3.2   NaN

In [74]:
val2 = pd.Series([-1.2,-1.5,-1.7],index=[0,3,5]) #更改DataFrame中的某一列的某个值

In [76]:
frame2["debt"] = val2

In [77]:
frame2

year State  pop  debt
0  2000  Ohio  1.5  -1.2
1  2001  Ohio  1.7   NaN
2  2002  Ohio  3.6   NaN
3  2001   Gui  2.4  -1.5
4  2002   Gui  2.9   NaN
5  2003   Gui  3.2  -1.7

In [78]:
frame2["eastern"] = frame2["State"]

In [79]:
frame2

year State  pop  debt eastern
0  2000  Ohio  1.5  -1.2    Ohio
1  2001  Ohio  1.7   NaN    Ohio
2  2002  Ohio  3.6   NaN    Ohio
3  2001   Gui  2.4  -1.5     Gui
4  2002   Gui  2.9   NaN     Gui
5  2003   Gui  3.2  -1.7     Gui

In [81]:
frame2["eastern"] = frame2["State"]=="Ohio"

In [82]:
frame2

year State  pop  debt  eastern
0  2000  Ohio  1.5  -1.2     True
1  2001  Ohio  1.7   NaN     True
2  2002  Ohio  3.6   NaN     True
3  2001   Gui  2.4  -1.5    False
4  2002   Gui  2.9   NaN    False
5  2003   Gui  3.2  -1.7    False

In [83]:
del frame2["eastern"]

In [86]:
frame2.columns

Index(['year', 'State', 'pop', 'debt'], dtype='object')

In [87]:
frame3 = frame2.copy()

In [88]:
frame3

year State  pop  debt
0  2000  Ohio  1.5  -1.2
1  2001  Ohio  1.7   NaN
2  2002  Ohio  3.6   NaN
3  2001   Gui  2.4  -1.5
4  2002   Gui  2.9   NaN
5  2003   Gui  3.2  -1.7

In [114]:
val3 = pd.Series([2,2,2],index=[1,2,4])

In [115]:
frame3["debt"]=val3

In [116]:
frame3

year State  pop  debt
0  2000  Ohio  1.5   NaN
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   2.0
3  2001   Gui  2.4   NaN
4  2002   Gui  2.9   2.0
5  2003   Gui  3.2   NaN

In [104]:
frame2

year State  pop  debt
0  2000  Ohio  1.5  -1.2
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   3.6
3  2001   Gui  2.4  -1.5
4  2002   Gui  2.9   2.9
5  2003   Gui  3.2  -1.7

In [94]:
frame2.iloc[0,3]

-1.2

In [95]:
frame2.iloc[1,3]=2

In [96]:
frame2

year State  pop  debt
0  2000  Ohio  1.5  -1.2
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   NaN
3  2001   Gui  2.4  -1.5
4  2002   Gui  2.9   NaN
5  2003   Gui  3.2  -1.7

In [117]:
frame3

year State  pop  debt
0  2000  Ohio  1.5   NaN
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   2.0
3  2001   Gui  2.4   NaN
4  2002   Gui  2.9   2.0
5  2003   Gui  3.2   NaN

In [118]:
frame3["debt"].fillna(frame3["pop"], inplace=True)

/var/folders/24/vsst64dn2h9b10q5jf4glt280000gn/T/ipykernel_66550/2320186893.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  frame3["debt"].fillna(frame3["pop"], inplace=True)


In [119]:
frame3

year State  pop  debt
0  2000  Ohio  1.5   1.5
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   2.0
3  2001   Gui  2.4   2.4
4  2002   Gui  2.9   2.0
5  2003   Gui  3.2   3.2

In [120]:
frame3.replace({"debt":{1.5:3,2:4}})

year State  pop  debt
0  2000  Ohio  1.5   3.0
1  2001  Ohio  1.7   4.0
2  2002  Ohio  3.6   4.0
3  2001   Gui  2.4   2.4
4  2002   Gui  2.9   4.0
5  2003   Gui  3.2   3.2

In [126]:
populations = {"Ohio":{2000:1.5,2001:1.7,2002:3.6},"Nevada":{2001:2.4,2002:2.9}}

In [122]:
frame4 = pd.DataFrame(populations)#未指定索引则内嵌字典的键作为索引

In [123]:
frame4

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [124]:
frame4.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [127]:
pd.DataFrame(populations,index=[2001,2002,2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [131]:
frame4["Ohio"]

2000    1.5
2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [133]:
pdata = {"Ohio":frame4["Ohio"][:-1],"Nevada":frame4["Nevada"][:2]}

In [134]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [135]:
frame3

year State  pop  debt
0  2000  Ohio  1.5   1.5
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   2.0
3  2001   Gui  2.4   2.4
4  2002   Gui  2.9   2.0
5  2003   Gui  3.2   3.2

In [140]:
frame3.index=[2000,2001,2002,2001,2002,2003]

In [141]:
frame3

year State  pop  debt
2000  2000  Ohio  1.5   1.5
2001  2001  Ohio  1.7   2.0
2002  2002  Ohio  3.6   2.0
2001  2001   Gui  2.4   2.4
2002  2002   Gui  2.9   2.0
2003  2003   Gui  3.2   3.2

In [143]:
frame3.rename(columns ={"debt":"abc"})

year State  pop  abc
2000  2000  Ohio  1.5  1.5
2001  2001  Ohio  1.7  2.0
2002  2002  Ohio  3.6  2.0
2001  2001   Gui  2.4  2.4
2002  2002   Gui  2.9  2.0
2003  2003   Gui  3.2  3.2

In [145]:
frame3

year State  pop  debt
2000  2000  Ohio  1.5   1.5
2001  2001  Ohio  1.7   2.0
2002  2002  Ohio  3.6   2.0
2001  2001   Gui  2.4   2.4
2002  2002   Gui  2.9   2.0
2003  2003   Gui  3.2   3.2

In [146]:
pdata2 = {"State":frame3["State"][:3],"pop":frame3["pop"][:-3],"debt":frame3["debt"][:3]}

In [147]:
pd.DataFrame(pdata2)

State  pop  debt
2000  Ohio  1.5   1.5
2001  Ohio  1.7   2.0
2002  Ohio  3.6   2.0

In [149]:
a = np.array([[1,2,4],[5,6,7],[2,1,5]])

In [150]:
a

array([[1, 2, 4],
       [5, 6, 7],
       [2, 1, 5]])

In [151]:
fa=pd.DataFrame(a,index=["a","b","c"],columns =["xx","yy","zz"] )

In [152]:
fa

xx  yy  zz
a   1   2   4
b   5   6   7
c   2   1   5

In [153]:
fa2=pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})

In [154]:
fa2

a  b
0  1  4
1  2  5
2  3  6

In [160]:
s1=pd.Series([1,2,3],index=["a","b","c"])

In [161]:
s1

a    1
b    2
c    3
dtype: int64

In [162]:
s2=pd.Series([6,8,2],index=["a","b","c"])

In [175]:
fa3=pd.DataFrame({"aa":s1[:2],"bb":s2[:2]},index=["a","b","c"])

In [176]:
fa3

aa   bb
a  1.0  6.0
b  2.0  8.0
c  NaN  NaN

In [177]:
frame4

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [178]:
frame4.index.name = "year"

In [179]:
frame4.columns.name = "State"

In [180]:
frame4

State  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [181]:
frame4.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [182]:
frame2

year State  pop  debt
0  2000  Ohio  1.5  -1.2
1  2001  Ohio  1.7   2.0
2  2002  Ohio  3.6   3.6
3  2001   Gui  2.4  -1.5
4  2002   Gui  2.9   2.9
5  2003   Gui  3.2  -1.7

In [183]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, 2.0],
       [2002, 'Ohio', 3.6, 3.6],
       [2001, 'Gui', 2.4, -1.5],
       [2002, 'Gui', 2.9, 2.9],
       [2003, 'Gui', 3.2, -1.7]], dtype=object)

In [192]:
labels = pd.Index(np.random.rand(3))

In [204]:
labels

Index([0.24964952656595785, 0.46071778577080047, 0.4042116963834399], dtype='float64')

In [210]:
labels.astype("float32")

Index([0.2496495246887207, 0.4607177972793579, 0.40421169996261597], dtype='float32')

In [211]:
obj2  = pd.Series([1.5,-2.5,0],index = labels)

In [212]:
obj2

0.249650    1.5
0.460718   -2.5
0.404212    0.0
dtype: float64