In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [8]:
fram3 = pd.DataFrame(np.array([[1.5,2],[1.7,2.4],[3.6,2.9]]),index=[2000,2001,2002],columns=["Ohio","Nevada"])

In [9]:
fram3

Ohio  Nevada
2000   1.5     2.0
2001   1.7     2.4
2002   3.6     2.9

In [10]:
frame3 =fram3

In [14]:
del frame3.iloc[0.1]

AttributeError: __delitem__

In [17]:
frame3.iloc[0,1]  = np.nan

In [18]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [20]:
frame3.index.name = "year"

In [22]:
frame3.columns.name = "state"

In [23]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [41]:
pd.isnull(frame3)

state   Ohio  Nevada
year                
2000   False    True
2001   False   False
2002   False   False

In [42]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [43]:
"Ohio" in frame3.columns

True

In [44]:
2002 in frame3.index


True

In [45]:
2003 in frame3.index

False

In [46]:
frame4 = pd.DataFrame(np.array([[3,2],[1.7,2],[3.6,3.9]]),index=[2002,2003,2004],columns=["Ohio","Nevada"])

In [47]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [48]:
frame3.index.append(frame4.index)

Index([2000, 2001, 2002, 2002, 2003, 2004], dtype='int64')

In [49]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [50]:
frame3.index

Index([2000, 2001, 2002], dtype='int64', name='year')

In [52]:
obj = pd.Series([4.5,7.2,5.3,-3.6],index=["b","d","c","a"])

In [53]:
obj

b    4.5
d    7.2
c    5.3
a   -3.6
dtype: float64

In [54]:
obj2 = obj.reindex(["a","b","c","d","e"])

In [55]:
obj2

a   -3.6
b    4.5
c    5.3
d    7.2
e    NaN
dtype: float64

In [57]:
obj3 = pd.Series(["blue","purple","yellow"],index = [0,2,4])

In [60]:
obj3.name = "colour"

In [61]:
obj3

0      blue
2    purple
4    yellow
Name: colour, dtype: object

In [63]:
obj3.reindex(np.arange(6),method = "ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
Name: colour, dtype: object

In [64]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index=["a","c","d"],columns = ["Ohio","Texas","California"])

In [65]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [66]:
frame2 = frame.reindex(index = ["a","b","c","d"])

In [67]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [71]:
state = ["Ohio","Utah","California"]

In [74]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [75]:
frame.reindex(columns=state)

Ohio  Utah  California
a     0   NaN           2
c     3   NaN           5
d     6   NaN           8

In [76]:
frame.reindex(state,axis = "columns")

Ohio  Utah  California
a     0   NaN           2
c     3   NaN           5
d     6   NaN           8

In [77]:
frame.reindex(["a","b","c"],axis = "index")

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0

In [78]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [80]:
frame.loc[["a","d","c"],["California","Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [81]:
obj = pd.Series(np.arange(5),index=["a","b","c","d","e"])

In [82]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [83]:
new_obj = obj.drop("c")

In [84]:
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [86]:
obj.drop(["a","c"])

b    1
d    3
e    4
dtype: int64

In [87]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [90]:
data = pd.DataFrame(np.arange(9).reshape(3,3),index=["a","b","c"],columns=["Ohio","Texas","California"])
data

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [91]:
data.drop(index=["a","c"])

Ohio  Texas  California
b     3      4           5

In [92]:
data.drop(["a","c"],axis = 0)

Ohio  Texas  California
b     3      4           5

In [95]:
data.drop(["a","c"],axis = "index")

Ohio  Texas  California
b     3      4           5

In [98]:
data.drop(columns=["California"])

Ohio  Texas
a     0      1
b     3      4
c     6      7

In [99]:
data.drop(["California"],axis=1)

Ohio  Texas
a     0      1
b     3      4
c     6      7

In [100]:
data.drop(["California"],axis="columns")

Ohio  Texas
a     0      1
b     3      4
c     6      7

In [102]:
data.drop(columns = ["California"],index=["a"])

Ohio  Texas
b     3      4
c     6      7

In [103]:
obj=pd.Series(np.arange(4.),index=["a","b","c","d"])

In [104]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [105]:
obj["a"]

0.0

In [106]:
obj[0]

/var/folders/24/vsst64dn2h9b10q5jf4glt280000gn/T/ipykernel_77124/1804121644.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[0]


0.0

In [107]:
obj[:-2]

a    0.0
b    1.0
dtype: float64

In [108]:
obj[-2:]

c    2.0
d    3.0
dtype: float64

In [111]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [112]:
obj[["a","d"]]

a    0.0
d    3.0
dtype: float64

In [115]:
obj.loc[["a","c"]]

a    0.0
c    2.0
dtype: float64

In [116]:
obj.loc[[1,2]]

KeyError: "None of [Index([1, 2], dtype='int64')] are in the [index]"

In [117]:
obj.iloc[[1,2]] #loc只使用标签；iloc只使用整数

b    1.0
c    2.0
dtype: float64

In [118]:
obj.loc["c":"d"] #loc切片包含末端

c    2.0
d    3.0
dtype: float64

In [120]:
obj.loc[["c","d"]]=5

In [121]:
obj

a    0.0
b    1.0
c    5.0
d    5.0
dtype: float64

In [123]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=["Ohio","Colorado","Utah","New York"],columns = ["one","two","three","four"])

In [124]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [142]:
data[0:1]

one  two  three  four
Ohio    0    1      2     3

In [147]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data[data[0:2]>2]

one  two  three  four
Ohio      NaN  NaN    NaN   3.0
Colorado  4.0  5.0    6.0   7.0
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [160]:
data[data[0:2]>2].dropna(how = "all",axis=0)

one  two  three  four
Ohio      NaN  NaN    NaN   3.0
Colorado  4.0  5.0    6.0   7.0

In [155]:
data[data["three"]>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [164]:
data[data<5]=0

In [165]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [166]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [169]:
data.loc[["Ohio","Utah"],["one","four"]]

one  four
Ohio    0     0
Utah    8    11

In [173]:
print(data.iloc[[0,2],[0,3]])#iloc右闭，可以取到右侧值
data.iloc[[0,3],[0,3]]

      one  four
Ohio    0     0
Utah    8    11


one  four
Ohio        0     0
New York   12    15

In [175]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [179]:
data[data["three"]>5]
data[data.three>5]  #两者等价

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [174]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [176]:
data.loc[data.three>=2] #loc可使用逻辑运算

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [180]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [188]:
data.reindex(["Utah","Ohio","Colorado","New York"],axis = 0)

one  two  three  four
Utah        8    9     10    11
Ohio        0    0      0     0
Colorado    0    5      6     7
New York   12   13     14    15

In [182]:
data.reindex(index=["Utah","Ohio","Colorado","New York"],columns=["four","two","three","one"])

four  two  three  one
Utah        11    9     10    8
Ohio         0    0      0    0
Colorado     7    5      6    0
New York    15   13     14   12

In [189]:
data.drop("four")

KeyError: "['four'] not found in axis"

In [190]:
data.drop(columns = "four")

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [191]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [194]:
data[data==0]=np.nan

In [195]:
data

one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   NaN   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [201]:
data.dropna(axis=0,how="all")

one   two  three  four
Colorado   NaN   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [202]:
data

one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   NaN   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [215]:
data=data.fillna(0)

In [228]:
data>0

one    two  three   four
Ohio      False  False  False  False
Colorado  False   True   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [234]:
data.loc[data.one>0,["one","two"]]

one   two
Utah       8.0   9.0
New York  12.0  13.0

In [237]:
data


one   two  three  four
Ohio       0.0   0.0    0.0   0.0
Colorado   0.0   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [238]:
data.iloc[1,0]=1

In [239]:
data

one   two  three  four
Ohio       0.0   0.0    0.0   0.0
Colorado   1.0   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [240]:
data[data>0]

one   two  three  four
Ohio       NaN   NaN    NaN   NaN
Colorado   1.0   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

In [261]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),index=["Ohio","Texas","Colorado"],columns = list("bcd"))

In [262]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),index=["Utah","Ohio","Texas","Oregon"],columns = list("bde"))

In [263]:
df1,df2

(            b    c    d
 Ohio      0.0  1.0  2.0
 Texas     3.0  4.0  5.0
 Colorado  6.0  7.0  8.0,
           b     d     e
 Utah    0.0   1.0   2.0
 Ohio    3.0   4.0   5.0
 Texas   6.0   7.0   8.0
 Oregon  9.0  10.0  11.0)

In [264]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [265]:
df1.add(df2,fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [267]:
df1 = pd.DataFrame({"A":[1,2]})

In [268]:
df2 = pd.DataFrame({"B":[3,4]})

In [269]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [270]:
df1.add(df2,fill_value=0)

A    B
0  1.0  3.0
1  2.0  4.0

In [271]:
df1

A
0  1
1  2

In [276]:
df1/3

A
0  0.333333
1  0.666667

In [277]:
3/df1

A
0  3.0
1  1.5

In [278]:
df1.div(3)

A
0  0.333333
1  0.666667

In [280]:
df1.rdiv(3)

A
0  3.0
1  1.5

In [281]:
arr = np.arange(12).reshape(3,4)

In [282]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [283]:
arr[0]

array([0, 1, 2, 3])

In [284]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [285]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),index=["Utah","Ohio","Texas","Oregon"],columns = list("bde"))

In [286]:
series=frame.iloc[0]

In [287]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [288]:
series 

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [289]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [294]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [290]:
series2=pd.Series(np.arange(3),index=["b","e","f"])

In [292]:
series2

b    0
e    1
f    2
dtype: int64

In [293]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [295]:
series3 = frame["d"]

In [296]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [298]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [300]:
frame-series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [302]:
frame.sub(series3,axis=0)#按行索引 axis=“index”

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0